### PR TITLE
Trim modules

### LINKED ISSUE #15: trim down to required modules
besu uses

    api 'io.tmio:tuweni-bytes:2.4.2'
    api 'io.tmio:tuweni-config:2.4.2'
    api 'io.tmio:tuweni-concurrent:2.4.2'
    api 'io.tmio:tuweni-crypto:2.4.2'
    api 'io.tmio:tuweni-devp2p:2.4.2'
    api 'io.tmio:tuweni-io:2.4.2'
    api 'io.tmio:tuweni-net:2.4.2'
    api 'io.tmio:tuweni-rlp:2.4.2'
    api 'io.tmio:tuweni-toml:2.4.2'
    api 'io.tmio:tuweni-units:2.4.2'

teku uses a subset of these plus ssz

tuweni-bytes
tuweni-crypto
tuweni-io
tuweni-rlp
tuweni-ssz
tuweni-units

### PR DESCRIPTION
**Pull request by lu-pinto**
## PR description
Trims down the project to only include the following modules, and others that these depend on:
```
tuweni-bytes
tuweni-config
tuweni-concurrent
tuweni-crypto
tuweni-devp2p
tuweni-io
tuweni-net
tuweni-rlp
tuweni-toml
tuweni-units
tuweni-ssz
```

## Fixed Issue(s)

fixes #15

### CODE REVIEW

**Review by garyschulte — APPROVED** [review]
OMMFG 

image

**Comment by garyschulte** [comment]
one thing though - I believe we invested in tuweni-ssz to make it robust enough for a besu ssz implementation.  We might want to keep that

**Comment by lu-pinto** [comment]
> one thing though - I believe we invested in tuweni-ssz to make it robust enough for a besu ssz implementation. We might want to keep that

Not sure I understand, I didn't remove `ssz`. So you want to keep or remove? Teku seems to be using it

**Comment by garyschulte** [comment]
> Not sure I understand, I didn't remove `ssz`. So you want to keep or remove? Teku seems to be using it

My bad - I read tuweni-ssz as removed, not kept. 👍

**Pull request merged**
